---
title: "Daros Ordinales"
author: "Brigido Vicuna"
date: "8/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
set.seed(2018)
clientes = sample(1:5, 50, replace = TRUE)
clientes
```
```{r}
set.seed(NULL)
clientes = ordered(clientes)
fabs = table(clientes)#Frecuencia Absoluta
fabs
frel = prop.table(table(clientes))#Frecuencia Relativa
frel
fabscum = cumsum(fabs)#Frecuencia Absoluta Acumulada
fabscum
frelcum = cumsum((frel))#Frecuencia Relativa Acumulada
frelcum

barplot(fabs, main = "Diagrama de barras de frecuencias absolutas")
```

```{r}
longitud = sample(c("Muy corto", "Corto", "Normal", "Largo", "Muy largo"), 100, replace = TRUE)

longitud = ordered(longitud, levels = c("Muy corto", "Corto", "Normal", "Largo", "Muy largo"))
longitud

fr.abs = table(longitud)
fr.abs

fr.rel = prop.table(fr.abs)
fr.rel

fr.abscum = cumsum(fr.abs)
fr.abscum

fr.relcum = cumsum(fr.rel)
fr.relcum

barplot(fr.abs, main = "Diagrama de barras de frecuencias absolutas")
barplot(fr.rel, main = "Diagrama de barras de frecuencias arelativas")
barplot(fr.abscum, main = "Diagrama de barras de frecuencias absolutas acumuladas")
barplot(fr.relcum, main = "Diagrama de barras de frecuencias relativas acumuladas")
```
```{r}
zonas = rep(c("A","B","C","D"),c(30,25,35,10))
jirafas = data.frame(zonas,longitud)
str(jirafas)
head(jirafas)
```

```{r}
apply(table(jirafas),MARGIN = 1, FUN = cumsum)#Frecuencia absoluta acumulada por fila

t(apply(table(jirafas),MARGIN = 1, FUN = cumsum)) 

t(apply(prop.table(table(jirafas), margin = 1), MARGIN = 1, FUN = cumsum))#Frecuencia relativa acumulada por fila

barplot(apply(table(jirafas),MARGIN = 1, FUN = cumsum), beside = T, legend = T, main = "Diagrama de frecuencias relativas acumuladas de longitudes por zonas",args.legend = list(x = "topleft", cex = 0.55))

```

```{r}
crabs = read.table("../data/datacrab.txt", header = TRUE)
crabs = crabs[,-1]#Omite la primera columna
str(crabs)
```
```{r}
table(crabs$width)

intervalos = cut(crabs$width, breaks = c(21,25,29,33,Inf), right = FALSE, labels = c("21-25", "25-29", "29-33", "33-..."))

crabs$width.rank = ordered(intervalos)
str(crabs)
```
```{r}
Tabla = table(crabs[,c(1,6)])#Frecuencias absolutas entre color y width.rank
Tabla
```
```{r}
Fr.rel = round(prop.table(Tabla, margin = 1),3)
Fr.rel
```
```{r}
Fr.rel.acum = round(apply(prop.table(Tabla,margin = 1), MARGIN = 1, FUN = cumsum),3)
t(Fr.rel.acum)
```
```{r}
azul = c("cyan", "cyan4", "cyan1", "cyan3")

barplot(t(Fr.rel), beside = TRUE, legend = TRUE, ylim = c(0,1), col = azul, 
        main = "Diagrama de barras de frecuencias relativas", 
        args.legend=list(x = "topright", cex=0.55))
```
```{r}
barplot(Fr.rel.acum, beside = TRUE, legend = TRUE, col = azul, 
        main = "Diagrama de barras de frecuencias relativas acumuladas", 
        args.legend=list(x = "topleft", cex=0.55))
```

