---
title: "Tarea3_Estructura de Datos"
author: "Brigido Vicuna"
date: "7/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Ejercicios para Estructura de Datos

## Ejercicio 1

### Dad la entrada (2,2) de A 路 (A + A) 路 A, con:

$$A = \begin{pmatrix}
1 & 3\\ 
2 & 4
\end{pmatrix} $$

```{r Ejercicio 1}
A = matrix(c(1,2,3,4),nrow = 2)#Definicion de la matriz A.

B = A%*%(A+A)%*%A #Sintaxis de A 路 (A + A) 路 A.
B
```

## Ejercicio 2

### Dad los valores propios de la matriz:

$$A = \begin{pmatrix}
2 & 4 & -6\\ 
0 & 0 & 3\\
0 & -2 & 5
\end{pmatrix} $$

```{r Ejercicio 2}
A = matrix(c(2,4,-6,0,0,3,0,-2,5), nrow=3, byrow=TRUE) #Definicion de la matriz A.
Avec = eigen(A)$vectors #Vectores propios de la matriz A.
Avec

```
## Ejercicio 3

### Dad, redondeando a 3 cifras decimales, los vectores propios de la matriz:

$$C = \begin{pmatrix}
-48 & 35 & -12\\ 
-134 & 95 & -32\\
-194 & 133 & -44
\end{pmatrix} $$

```{r Ejercicio 3}
C = matrix(c(-48,35,-12,-134,95,-32,-194,133,-44), nrow=3, byrow=TRUE) #Definicion de la matriz C
Cvec = round(eigen(C)$vectors,3)#Vectores propios de la matriz C redondeados a 3 decimales.
Cvec
```
## Ejercicio 4

### Dad el rango de la matriz:

$$C = \begin{pmatrix}
-2 & -8 & -2 & 3\\ 
-3 & -6 & -1 & 2\\
-9 & -22 & -3 & 7\\
-18 & -44 & -8 & 15
\end{pmatrix} $$

```{r Ejericio 4}
C = matrix(c(-2,-8,-2,3,-3,-6,-1,2,-9,-22,-3,7,-18,-44,-8,15), nrow=4, byrow=TRUE) #Definicion de la matriz C
Crank = qr(C)$rank #Calculo del rango de la matriz C.
Crank
```

